"""empty message

Revision ID: 57cfabc88321
Revises: 
Create Date: 2019-10-15 16:18:20.526272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
import core

revision = '57cfabc88321'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('status', sa.Integer(), nullable=False),
        sa.Column('full_name', sa.String(length=32), nullable=True),
        sa.Column('email', sa.String(length=256), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
        sa.Column('hashed_password', sa.String(length=36), nullable=False),
        sa.Column('meta', core.src.database.json_column_type(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_full_name'), ['full_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_hashed_password'), ['hashed_password'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_status'))
        batch_op.drop_index(batch_op.f('ix_user_hashed_password'))
        batch_op.drop_index(batch_op.f('ix_user_full_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
